attitudinal:
  ches2019:
    -
  gps2019:
    -
  ches2023:
    -
ideological:
  cbar_rect:
  - 0.15
  - 0.35
  - 0.03
  - 0.45
  legend_loc: upper right
  limits:
    x:
    - -2
    - 4
    y:
    - -2
    - 4
  nudges:
    party:
    - 0
    - 0
palette:
  false